package org.openpendant.app

import org.junit.Assert.*
import org.junit.Test
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.io.InputStream
import java.io.OutputStream
import java.io.IOException

/** Generated bytes only. No documents, owner keys, URI grants or Android APIs. */
class RecoveryDocumentIOTest {
    private fun fixture() = ByteArray(145) { (it % 127).toByte() }
    private fun rejected(block: () -> Unit) {
        try { block(); fail("Expected bounded document failure") }
        catch (error: RecoveryDocumentException) {
            assertEquals("Recovery document operation failed", error.message)
            assertNull(error.cause)
        }
    }

    @Test fun exactSizeReadReturnsRedactedOwnedCopyWithoutClosingCallerStream() {
        var closed = false
        val input = object : ByteArrayInputStream(fixture()) {
            override fun close() { closed = true; super.close() }
        }
        RecoveryDocumentIO.readBackup(input).use { backup ->
            assertArrayEquals(fixture(), backup.copyForExplicitExport())
            assertEquals("RecipientRecoveryBytes[REDACTED]", backup.toString())
        }
        assertFalse(closed)
    }

    @Test fun partialAndZeroBulkReadsAreBoundedWithoutLosingBytes() {
        val source = fixture()
        var position = 0
        var calls = 0
        val input = object : InputStream() {
            override fun read(): Int = if (position == source.size) -1 else source[position++].toInt() and 255
            override fun read(bytes: ByteArray, offset: Int, length: Int): Int {
                calls++
                if (calls % 2 == 0) return 0
                if (position == source.size) return -1
                val count = minOf(3, length, source.size - position)
                source.copyInto(bytes, offset, position, position + count); position += count
                return count
            }
        }
        RecoveryDocumentIO.readBackup(input).use { assertArrayEquals(source, it.copyForExplicitExport()) }
        assertTrue(calls <= 145)
    }

    @Test fun allTruncationsAndTrailingDataAreRejectedAfterAtMost146Bytes() {
        for (length in 0 until 145) rejected { RecoveryDocumentIO.readBackup(ByteArrayInputStream(fixture().copyOf(length))).close() }
        for (length in listOf(146, 4096)) {
            val input = ByteArrayInputStream(ByteArray(length))
            rejected { RecoveryDocumentIO.readBackup(input).close() }
            assertEquals(length - 146, input.available())
        }
    }

    @Test fun readFailureWipesBufferAndDoesNotExposeProviderMessage() {
        var retained: ByteArray? = null
        val input = object : InputStream() {
            override fun read(): Int = -1
            override fun read(bytes: ByteArray, offset: Int, length: Int): Int {
                retained = bytes; bytes.fill(42)
                throw IOException("synthetic-secret-provider-detail")
            }
        }
        rejected { RecoveryDocumentIO.readBackup(input).close() }
        assertTrue(retained!!.all { it == 0.toByte() })
    }

    @Test fun writeUsesExactBytesFlushesAndWipesItsTemporaryCopy() {
        val capture = ByteArrayOutputStream()
        var retained: ByteArray? = null
        var flushed = false
        var closed = false
        val output = object : OutputStream() {
            override fun write(value: Int) { capture.write(value) }
            override fun write(bytes: ByteArray) { retained = bytes; capture.write(bytes) }
            override fun flush() { flushed = true }
            override fun close() { closed = true }
        }
        RecipientRecoveryBytes(fixture()).use { RecoveryDocumentIO.writeBackup(output, it) }
        assertArrayEquals(fixture(), capture.toByteArray())
        assertTrue(flushed); assertFalse(closed)
        assertTrue(retained!!.all { it == 0.toByte() })
    }

    @Test fun failedAndClosedExportsNeverLeakDetailsAndWipeTemporaryCopy() {
        var retained: ByteArray? = null
        val output = object : OutputStream() {
            override fun write(value: Int) { throw IOException("synthetic-secret-detail") }
            override fun write(bytes: ByteArray) { retained = bytes; throw IOException("synthetic-secret-detail") }
        }
        RecipientRecoveryBytes(fixture()).use { rejected { RecoveryDocumentIO.writeBackup(output, it) } }
        assertTrue(retained!!.all { it == 0.toByte() })
        val closed = RecipientRecoveryBytes(fixture()); closed.close()
        rejected { RecoveryDocumentIO.writeBackup(output, closed) }
    }
}
