cmake_minimum_required(VERSION 3.22)
if(NOT IS_DIRECTORY "${OPUS_VENDOR}" OR IS_SYMLINK "${OPUS_VENDOR}")
  message(FATAL_ERROR "Pinned Opus source directory missing or linked")
endif()
file(READ "${CMAKE_CURRENT_LIST_DIR}/opus-source-pins.json" _pins)
string(JSON _count LENGTH "${_pins}" files)
if(NOT _count EQUAL 482)
  message(FATAL_ERROR "Opus source pin count differs")
endif()
file(GLOB_RECURSE _actual LIST_DIRECTORIES false "${OPUS_VENDOR}/*")
list(LENGTH _actual _actual_count)
if(NOT _actual_count EQUAL _count)
  message(FATAL_ERROR "Opus source set differs")
endif()
math(EXPR _last "${_count}-1")
foreach(_i RANGE 0 ${_last})
  string(JSON _path GET "${_pins}" files ${_i} path)
  string(JSON _expected GET "${_pins}" files ${_i} sha256)
  if(_path MATCHES "(^/|\\\\|(^|/)\\.\\.(/|$)|:)" OR
     IS_SYMLINK "${OPUS_VENDOR}/${_path}" OR NOT EXISTS "${OPUS_VENDOR}/${_path}")
    message(FATAL_ERROR "Invalid pinned Opus file")
  endif()
  file(SHA256 "${OPUS_VENDOR}/${_path}" _actual_hash)
  if(NOT _actual_hash STREQUAL _expected)
    message(FATAL_ERROR "Pinned Opus source checksum differs")
  endif()
endforeach()
