#include "crypto_public_test.h"
#include "encrypted_segment_header.h"
#include "recording_hpke_psa.h"
#include <string.h>

static struct recording_hpke_psa_context owner = RECORDING_HPKE_PSA_CONTEXT_INIT;
static int attempted;
/* Published RFC 9180 recipient PUBLIC point. No recipient private key is
 * compiled into the target. The real ephemeral private keys are generated by
 * the audited PSA CSPRNG, never by a deterministic diagnostic hook. */
static const uint8_t recipient[65] = {
    0x04,0xab,0xc7,0xe4,0x9a,0x4c,0x6b,0x35,0x66,0xd7,0x7d,0x03,0x04,0xad,0xdc,0x6e,
    0xd0,0xe9,0x85,0x12,0xff,0xcc,0xf5,0x05,0xe6,0xa8,0xe3,0xeb,0x25,0xc6,0x85,0x13,
    0x6f,0x85,0x31,0x48,0x54,0x48,0x76,0xde,0x76,0xc0,0xf2,0xef,0x99,0xcd,0xc3,0xa0,
    0x5c,0xcf,0x5d,0xed,0x78,0x60,0xc7,0xc0,0x21,0x23,0x8f,0x9e,0x20,0x73,0xd2,0x35,0x6c
};
static const struct es_binding fixed_binding = {
    .key_fingerprint = {
        0x74,0x45,0x1b,0xdc,0x1f,0xe4,0xab,0xf6,0x07,0x78,0x3b,0xc8,0xb2,0x24,0xc7,0x5f,
        0x4b,0x80,0x9e,0xe3,0xc1,0x56,0x10,0xd5,0x6e,0x6c,0xb4,0xf0,0x0e,0xb1,0x23,0x22 },
    .device_id = {0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1a,0x1b,0x1c,0x1d,0x1e,0x1f,0x20},
    .volume_id = {0x21,0x22,0x23,0x24,0x25,0x26,0x27,0x28,0x29,0x2a,0x2b,0x2c,0x2d,0x2e,0x2f,0x30},
    .recording_id = {0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38,0x39,0x3a,0x3b,0x3c,0x3d,0x3e,0x3f,0x40},
    .generation = UINT64_C(0x0102030405060708),
    .segment_sequence = 7u, .plaintext_bytes = 29u
};
static const uint8_t public_text[] = "Beauty is truth, truth beauty";
static const uint8_t kat_message[] = "OpenPendant public crypto KAT v1";
/* Separate members guarantee non-overlapping spans even with constant merging. */
static const struct { uint8_t key[32], nonce[12], plaintext[16], aad[1]; } kat = {0};
static const uint8_t expected_mac[32] = {
    0xcd,0xf5,0x77,0x97,0x4b,0x6a,0x8e,0xba,0xbb,0x49,0x16,0xe3,0x84,0x3b,0xb8,0x93,
    0x80,0xf7,0x2b,0xe2,0xd0,0xb3,0x43,0x45,0x57,0x6c,0x57,0x40,0x33,0x0b,0x48,0x91
};
static const uint8_t expected_aes[32] = {
    0xce,0xa7,0x40,0x3d,0x4d,0x60,0x6b,0x6e,0x07,0x4e,0xc5,0xd3,0xba,0xf3,0x9d,0x18,
    0xd0,0xd1,0xc8,0xa7,0x99,0x99,0x6b,0xf0,0x26,0x5b,0x98,0xb5,0xd4,0x8a,0xb9,0x19
};

static void wipe(void *buffer, size_t bytes)
{
    volatile uint8_t *p = buffer;
    while (bytes != 0u) { *p++ = 0u; --bytes; }
}

int crypto_public_test_run(struct crypto_public_result *out)
{
    struct es_binding binding = fixed_binding;
    uint8_t info[ES_INFO_BYTES] = {0}, answer[32] = {0};
    const struct recording_hpke_provider *provider;
    size_t actual = 0;
    int rc = -1;
    if (out == NULL || attempted) { return -7; }
    attempted = 1;
    memset(out, 0, sizeof(*out));
    if (recording_hpke_psa_init(&owner) != RECORDING_HPKE_OK) { goto done; }
    provider = recording_hpke_psa_provider(&owner);
    rc = -2;
    if (provider == NULL ||
        provider->hmac_sha256(provider->user, kat.key, sizeof(kat.key), kat_message,
            sizeof(kat_message)-1u, answer, sizeof(answer), &actual) != RECORDING_HPKE_OK ||
        actual != sizeof(answer) || memcmp(answer, expected_mac, sizeof(answer)) != 0) { goto done; }
    wipe(answer, sizeof(answer)); actual = 0;
    if (provider->aes256gcm_seal(provider->user, kat.key, sizeof(kat.key),
            kat.nonce, sizeof(kat.nonce), kat.aad, 0u, kat.plaintext, sizeof(kat.plaintext),
            answer, sizeof(answer), &actual) != RECORDING_HPKE_OK ||
        actual != sizeof(answer) || memcmp(answer, expected_aes, sizeof(answer)) != 0) { goto done; }
    wipe(answer, sizeof(answer));
    for (uint32_t i = 0; i < CRYPTO_PUBLIC_CONTAINER_COUNT; ++i) {
        uint8_t *container = out->containers[i];
        binding.segment_sequence = 7u + i;
        rc = -3;
        if (es_header_build(container, ES_HEADER_BYTES, &binding) != ES_OK ||
            es_info_build(info, sizeof(info), container, ES_HEADER_BYTES, &binding) != ES_OK) { goto done; }
        actual = 0; rc = -4;
        if (recording_hpke_psa_seal(&owner, recipient, sizeof(recipient), info, sizeof(info),
                NULL, 0u, public_text, sizeof(public_text)-1u,
                container + ES_HEADER_BYTES, ES_ENCAP_BYTES,
                container + ES_HEADER_BYTES + ES_ENCAP_BYTES,
                sizeof(public_text)-1u + ES_TAG_BYTES, &actual) != RECORDING_HPKE_OK ||
            actual != sizeof(public_text)-1u + ES_TAG_BYTES ||
            es_container_validate(container, CRYPTO_PUBLIC_CONTAINER_BYTES, &binding) != ES_OK) { goto done; }
        ++out->completed;
    }
    rc = -5;
    if (memcmp(out->containers[0] + ES_HEADER_BYTES,
               out->containers[1] + ES_HEADER_BYTES, ES_ENCAP_BYTES) == 0) { goto done; }
    rc = 0;
done:
    out->owner_faulted = recording_hpke_psa_faulted(&owner);
    if (out->owner_faulted) { rc = -6; }
    out->error = rc;
    if (rc != 0) { wipe(out->containers, sizeof(out->containers)); out->completed = 0; }
    wipe(info, sizeof(info)); wipe(answer, sizeof(answer));
    return rc;
}
