/* SPDX-License-Identifier: Apache-2.0 */
#ifndef OPENPENDANT_RECORDING_LARGE_LAYOUT_H
#define OPENPENDANT_RECORDING_LARGE_LAYOUT_H
/* Fixed new-volume layout, never inferred from old on-disk geometry. */
#define RLL_BLOCKS 2048U
#define RLL_CAPACITY 94208U
#define RLL_ROOTS 32U
#define RLL_SLOTS 5120U
#define RLL_SLOT_PAGES 18U
#define RLL_ROS_CAPACITY (RLL_ROOTS+RLL_SLOTS*RLL_SLOT_PAGES)
#define RLL_RECEIPTS_PER_PAGE 32U
#define RLL_RECEIPT_PAGES ((RLL_SLOTS+31U)/32U)
#define RLL_TOMBSTONES 512U
#define RLL_TOMBSTONES_PER_PAGE 14U
#define RLL_TOMBSTONE_PAGES ((RLL_TOMBSTONES+13U)/14U)
#define RLL_RECEIPT_BASE RLL_ROS_CAPACITY
#define RLL_TOMBSTONE_BASE (RLL_RECEIPT_BASE+RLL_RECEIPT_PAGES)
#define RLL_METADATA_ROOT (RLL_CAPACITY-1U)
_Static_assert(RLL_TOMBSTONE_BASE+RLL_TOMBSTONE_PAGES<RLL_METADATA_ROOT,"Metadata regions must not overlap");
_Static_assert(RLL_SLOTS<65536U,"Slot indexes fit u16");
#endif
