# Keep the network recovery bootloader minimal and its SWD available.
CONFIG_NCS_SAMPLES_DEFAULTS=n
CONFIG_LOG=n
CONFIG_LOG_MODE_MINIMAL=n
CONFIG_SECURE_BOOT_VALIDATION_LOG_LEVEL_INF=n
CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n
CONFIG_PRINTK=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_ASSERT=n
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_NRF_APPROTECT_USE_UICR=y
CONFIG_NRF_APPROTECT_LOCK=n
CONFIG_PCD_LOCK_NETCORE_DEBUG=n
